[package]
name = "fayd"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }

bdk_bitcoind_rpc = "0.6"
bdk = "1.0.0-alpha.7"
bdk_file_store = "0.7"
